### ISSUE TITLE
优化

### ISSUE THREAD

**Issue by lql0101** [LEODPEN/Where-is-my-tab#4]
1.建议优化新开tab下的输入栏。输入框中的`Please enter keywords`需要手动删除后才能输入。
![image](https://user-images.githubusercontent.com/52629246/119637214-02dea300-be48-11eb-8a8b-03dc0bc8d1a5.png)
2.在没有tab匹配输入关键字时，建议给出无效反馈。
3.u1s1，新开tab的灰色图标感觉有点尬。
![image](https://user-images.githubusercontent.com/52629246/119638335-222a0000-be49-11eb-88d5-5cd9cb0169c1.png)

**Comment by LEODPEN** [comment]
建议直接Ctrl + shift+ 9 打开popup页面，不建议新开tab页。

**Comment by LEODPEN** [comment]
无显示代表没有匹配，感觉无须优化或者暂时优先级较低，看看有无其他人有类似诉求吧。

**Comment by LEODPEN** [comment]
突然想起来了，之前优化好了ql
